Vapor/Vapor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
	url(r'^home/', include('home.urls', namespace="home", app_name="home")),
	url(r'^search/', include('search.urls', namespace="search", app_name="search")),
	url(r'^cart/', include('cart.urls', namespace="cart", app_name="cart")),
	url(r'^create/', include('create.urls', namespace="create", app_name="create")),
	url(r'^$', RedirectView.as_view(url='home/')),
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace="user", app_name= "user")),
]

Vapor/cart/urls.py
from django.conf.urls import url
from . import views

app_name = "reports"

urlpatterns = [
	url(r'^', views.cart_view, name="cart_view"),
]

Vapor/user/urls.py
	
from django.conf.urls import url, include
from django.contrib import admin
from . import views

#Add Django site authentication urls (for login, logout, password management)
urlpatterns = [
    url(r'^accounts/', include('django.contrib.auth.urls')), 	
   	url(r'^register/$', views.register_user, name='register-user'),
    url(r'^confirm/(?P<activation_key>\w+)/$', views.register_confirm, name='register-confirm'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),

]

Vapor/user/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.template.context_processors import csrf
from django.forms.models import inlineformset_factory

CATEGORIES = (
    ('Investor User', 'Investor User'),
    ('Company User', 'Company User'),
)

class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254, help_text='Please enter a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

Vapor/user/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.shortcuts import redirect
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View, ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.models import User, Group, Permission
from django.template.context_processors import csrf
from django.template import RequestContext
from django.utils import timezone
from django.db.models import Q
from django.utils import timezone
from django.db.models import Max
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, resolve_url
from django.contrib.contenttypes.models import ContentType
from django.core.mail import send_mail

import json
import datetime
import random
import hashlib

from data.models import Customer
from .forms import RegistrationForm
from .forms import UserForm


# Create your views here.
from data.models import Customer
from .forms import RegistrationForm



def user_login(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
    else:
        return render(request, 'user/login.html', {})

def register_user(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            email = form.cleaned_data['email']

            temp_customer = Customer(customer_name=username)
            temp_customer.save()
            # user_type = form.cleaned_data['user_type']

            # random_string = str(random.random()).encode('utf8')
            # salt = hashlib.sha1(random_string).hexdigest()[:5]
            # salted = (salt + email).encode('utf8')
            # activation_key = hashlib.sha1(salted).hexdigest()
            # key_expires = timezone.now() + datetime.timedelta(2)

            # customer = User.objects.get(username=username)

            # customer_profile = Customer(id=customer.id, customer_name = username)
            # customer_profile.save()

            # email_subject = 'Vapor Registration Confirmation'

            # email_message = "Thank you for signing up with Vapor! To activate your account, please visit: \
            #     http://127.0.0.1:8000/users/login/"

            # send_mail(email_subject, email_message, 'rt4hc@gmail.com', [email], fail_silently=False)

            customer = authenticate(username=username, password=raw_password)
            login(request, customer)
            return redirect('/')
    else:
        form = RegistrationForm()
    return render(request, 'user/register.html', {'form': form})

def register_confirm(request, activation_key):
    if request.user.is_authenticated():
        HttpResponseRedirect('http://127.0.0.1:8000/')

    customer_profile = get_object_or_404(Customer)

    # if customer_profile.key_expires < timezone.now():
    #     return HttpResponse("Activation key not working! Please register a new account.")

    customer = customer_profile.customer
    customer.is_active = True
    customer.save()
    return HttpResponse("Registration successful! Please go to the login page to log in to your account!")

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/user/login/')

Vapor/user/templates/user/logged_out.html
{% block content %}
{% load static %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="{% static "css/index/index.css" %}">
{% include "index/navbar.html" %
<p>You are logged out of Vapor!</p>  

<a href="{% url 'user:login'%}">Click here to login again.</a>
{% endblock %}

Vapor/user/templates/user/login.html
{% block content %}
{% load static %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="{% static "css/home/home.css" %}">
{% include "home/navbar.html" %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 center-block" style="float: none">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1>Vapor Login</h1>
                </div>
                <div class="panel-body">
                    <form id="login_form" method="post" action="{% url 'user:login' %}">
                        {% csrf_token %}
                        <div class="form-group input-group col-md-12">
                            <span class="input-group-addon" id="basic-addon1">
                                <span class="glyphicon glyphicon-user"></span>
                            </span>
                            <input class="form-control" type="text" name="username" value="" placeholder="Username" size="50" aria-describedby="basic-addon1"/><br />
                        </div>
                        <div class="form-group input-group col-md-12">
                            <span class="input-group-addon" id="basic-addon2">
                                <span class="glyphicon glyphicon-lock"></span>
                            </span>
                            <input class="form-control" type="password" name="password" value="" placeholder="Password" size="50" aria-describedby="basic-addon2"/><br />
                        </div>
                        <div class="form-group">
                            <input class="btn btn-primary col-md-12" type="submit" value="Login" />
                        </div>
                    </form>
                </div>
            </div>
            </div>
        </div><!-- END ROW
    <!-- </div> -->

{% endblock %}

Vapor/user/templates/user/register.html
{% block content %}
{% load static %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="{% static "css/index/index.css" %}">
{% include "home/navbar.html" %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}