Vapor/Vapor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
	url(r'^home/', include('home.urls', namespace="home", app_name="home")),
	url(r'^search/', include('search.urls', namespace="search", app_name="search")),
	url(r'^cart/', include('cart.urls', namespace="cart", app_name="cart")),
	url(r'^create/', include('create.urls', namespace="create", app_name="create")),
	url(r'^$', RedirectView.as_view(url='home/')),
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace="user", app_name= "user")),
]

Vapor/cart/urls.py
from django.conf.urls import url
from . import views

app_name = "reports"

urlpatterns = [
	url(r'^', views.cart_view, name="cart_view"),
]

Vapor/search/urls.py
from django.conf.urls import url 
from . import views

app_name = "search"

urlpatterns = [
	url(r'^product/(?P<product_id>[0-9]+)', views.detail_view, name='detailview'),
	url(r'^results$', views.results_view, name='resultsview'),
	url(r'', views.search_view, name='searchview'),
]

Vapor/search/forms.py
from django import forms
from data.models import Customer

class AddToCartForm(forms.Form):
	customer = forms.ModelChoiceField(queryset=Customer.objects.all(), empty_label="Who are you?")

Vapor/search/views.py
from django.shortcuts import render, redirect
from data.models import Product, Merchant, Developer, Customer, ShoppingCart, Review
from .forms import AddToCartForm

# Create your views here.

def detail_view(request, product_id):
	context = {}
	product = Product.objects.get(id=product_id)
	context['product'] = product

	reviews = Review.objects.filter(product_id=product_id)
	context['reviews'] = reviews
	print(reviews)

	# for when user clicks 'add to cart'
	if request.method == "POST":
		form = AddToCartForm(request.POST)
		if request.POST.get('add_cart'):
			if form.is_valid():
				cform = form.cleaned_data
				customer = cform['customer']

				sc = ShoppingCart(product_id=product, customer_id=customer)
				sc.save()
				return redirect('/cart/'+str(customer.id))

	else:
		form = AddToCartForm()

	context['form'] = form


	return render(request, 'search/detailview.html', context)

def search_view(request):
	context = {'is_logged_in':True}

	if request.method == "POST":
		if request.POST.get('search_button'):
			name_search = request.POST.get('name_search')
			price_mod = request.POST.get('price_mod')
			price_search = request.POST.get('price_search')
			genre_search = request.POST.get('genre_search')
			merch_search = request.POST.get('merch_search')
			dev_search = request.POST.get('dev_search')

		qset = Product.objects.all()
		if name_search:
			qset = qset.filter(product_name=name_search)
		if price_mod and price_search:
			if price_mod == 'less':
				qset = qset.filter(price__lt=price_search)
			elif price_mod == 'greater':
				qset = qset.filter(price__gt=price_search)
			else:
				qset = qset.filter(price=price_search)
		if genre_search:
			qset = qset.filter(genre=genre_search)
		if merch_search:
			try:
				merch = Merchant.objects.get(merchant_name=merch_search)
				qset = qset.filter(merchant_id=merch)
			except:
				print("merchant not found")
		if dev_search:
			try:
				dev = Developer.objects.get(developer_name=dev_search)
				qset = qset.filter(developer_id=dev)
			except:
				print("developer not found")

		data = []
		for item in qset:
			data.append(item)

		request.session['search_results'] = data

		return redirect('/search/results')

	return render(request, 'search/searchview.html', context)

def results_view(request):
	print("render results")
	data = request.session['search_results']
	context = {'results': data}

	if request.method == "POST":
		view_prod_id = request.POST.get('prod_id')

		return redirect('/search/product/' + view_prod_id)

	return render(request, 'search/resultsview.html', context)

Vapor/search/templates/search/detailview.html
{% block content %}
{% load static %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="{% static 'css/home/home.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'search/style.css' %}" />

{% include "home/navbar.html" %}


<div class='l-margin'>
	<h1> Product Details </h1>

	<table>
		<tbody>
			<tr>
				<td> Product Name: </td>
				<td> {{ product.product_name }} </td>
			</tr>
			<tr>
				<td> Price: </td>
				<td> $ {{ product.price }} </td>
			</tr>
			<tr>
				<td> Amount in stock: </td>
				<td> {{ product.stock }} </td>
			</tr>
			<tr>
				<td> Genre: </td>
				<td> {{ product.genre }} </td>
			</tr>
			<tr>
				<td> Release Date: </td>
				<td> {{ product.release_date }} </td>
			</tr>
			<tr>
				<td> Description: </td>
				<td> {{ product.product_description }} </td>
			</tr>
			<tr>
				<td> Developer: </td>
				<td> {{product.developer_id.developer_name }} </td>
			</tr>
			<tr>
				<td> Sold by: </td>
				<td> {{ product.merchant_id.merchant_name }} </td>
			</tr>
		</tbody>
	</table>

	<div style="border-bottom: 3px solid black; margin: 5px; width: 300px"> </div>
	<form method="post">
		{% csrf_token %}

		{{ form.customer }}

		<input type="submit" name="add_cart" value="Add to Cart">
	</form>

	{% if reviews %}
		<h2> reviews: </h2>
		{% for review in reviews %}
			{{review.review_content}}
		{% endfor %}

	{% else %}
	<div> No reviews yet </div>
	{% endif %}
</div>

{% endblock %}

Vapor/search/templates/search/resultsview.html
{% block content %}
{% load static %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="{% static 'css/home/home.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'search/style.css' %}" />

{% include "home/navbar.html" %}

<div class='l-margin'>
	<h1> Search Results </h1>

	{% for item in results %}
		{{ item.product_name }}
		<form method='post'>
			{% csrf_token %}
			<input type="hidden" value={{item.id}} name="prod_id" />
			<input type="submit" value="View Details" name="view_details" />
		</form>
	{% endfor %}

	<a href="{% url 'search:searchview' %}"> back </a>
</div>

{% endblock %}

Vapor/search/templates/search/searchview.html
{% block content %}
{% load static %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="{% static 'css/home/home.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'search/style.css' %}" />

{% include "home/navbar.html" %}


<div class='l-margin'>
	<h1 class="search_title"> Search for Products </h1>
	<form method="post">
		{% csrf_token %}

		<table>
			<tbody>
				<tr>
					<td>
						<div class='custom_container'>
							Product Name:
							<input class="r-align" type="text" placeholder="search by product name" name="name_search" size="30" />
						</div>
					</td>
					<td>
						<div class='custom_container'>
							Merchant: 
							<input class='r-align' type="text" placeholder="search by merchant" name="merch_search" size="30" />
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class='custom_container'>
							Price: 
							<input class='r-align' type="text" placeholder="search by price" name="price_search" size="30" />
							<div class='price_comparision'>
								<input type="radio" name="price_mod" value="less" /> Less than (<)
								&nbsp; 
								<input type="radio" name="price_mod" value="greater" /> Greater than (>)
								&nbsp; 
								<input type="radio" name="price_mod" value="equal" /> Equal to (=)
							</div>
						</div>
					</td>
					<td>
						<div class='custom_container'>
							Developer:
							<input class='r-align' type="text" placeholder="search by developer" name="dev_search" size="30" />
						</div>
					</td>
				</tr>
				<tr>
					<td> </td>
					<td>
						<div class='custom_container'>
							Genre:
							<div class='price_comparison'>
								<input type="radio" name="genre_search" value="Genre1" /> Genre 1
								<input type="radio" name="genre_search" value="Genre2" /> Genre 2
								<input type="radio" name="genre_search" value="Genre3" /> Genre 3
							</div>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
		<input type="submit" value="search" name="search_button" />
	</form>
</div>


{% endblock %}